
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vbox3;
	private global::Gtk.VBox vbox4;
	private global::Gtk.HBox hbox2;
	private global::Gtk.Label lblEntryName;
	private global::Gtk.Entry txtEntry;
	private global::Gtk.Label lblEntryDescription;
	private global::Gtk.ScrolledWindow GtkScrolledWindow1;
	private global::Gtk.TextView txtEntryDescription;
	private global::Gtk.Calendar CalendarEntryDate;
	private global::Gtk.Label lblEntries;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView txtAllEntryDescription;
	private global::Gtk.HBox hbox1;
	private global::Gtk.Button btnAddEntry;
	private global::Gtk.Button btnExit;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 4;
		// Container child vbox4.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.lblEntryName = new global::Gtk.Label ();
		this.lblEntryName.Name = "lblEntryName";
		this.lblEntryName.LabelProp = global::Mono.Unix.Catalog.GetString ("Entry name: ");
		this.hbox2.Add (this.lblEntryName);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.lblEntryName]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.txtEntry = new global::Gtk.Entry ();
		this.txtEntry.CanFocus = true;
		this.txtEntry.Name = "txtEntry";
		this.txtEntry.IsEditable = true;
		this.txtEntry.InvisibleChar = '•';
		this.hbox2.Add (this.txtEntry);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.txtEntry]));
		w2.Position = 1;
		this.vbox4.Add (this.hbox2);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox2]));
		w3.Position = 0;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.lblEntryDescription = new global::Gtk.Label ();
		this.lblEntryDescription.Name = "lblEntryDescription";
		this.lblEntryDescription.LabelProp = global::Mono.Unix.Catalog.GetString ("Entry Description: ");
		this.vbox4.Add (this.lblEntryDescription);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.lblEntryDescription]));
		w4.Position = 1;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.txtEntryDescription = new global::Gtk.TextView ();
		this.txtEntryDescription.CanFocus = true;
		this.txtEntryDescription.Name = "txtEntryDescription";
		this.GtkScrolledWindow1.Add (this.txtEntryDescription);
		this.vbox4.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow1]));
		w6.Position = 2;
		// Container child vbox4.Gtk.Box+BoxChild
		this.CalendarEntryDate = new global::Gtk.Calendar ();
		this.CalendarEntryDate.CanFocus = true;
		this.CalendarEntryDate.Name = "CalendarEntryDate";
		this.CalendarEntryDate.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
		this.vbox4.Add (this.CalendarEntryDate);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.CalendarEntryDate]));
		w7.Position = 3;
		w7.Expand = false;
		w7.Fill = false;
		this.vbox3.Add (this.vbox4);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.vbox4]));
		w8.Position = 0;
		// Container child vbox3.Gtk.Box+BoxChild
		this.lblEntries = new global::Gtk.Label ();
		this.lblEntries.Name = "lblEntries";
		this.lblEntries.LabelProp = global::Mono.Unix.Catalog.GetString ("All entries for the selected month:");
		this.vbox3.Add (this.lblEntries);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.lblEntries]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.txtAllEntryDescription = new global::Gtk.TextView ();
		this.txtAllEntryDescription.CanFocus = true;
		this.txtAllEntryDescription.Name = "txtAllEntryDescription";
		this.GtkScrolledWindow.Add (this.txtAllEntryDescription);
		this.vbox3.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow]));
		w11.Position = 2;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 9;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnAddEntry = new global::Gtk.Button ();
		this.btnAddEntry.CanFocus = true;
		this.btnAddEntry.Name = "btnAddEntry";
		this.btnAddEntry.UseUnderline = true;
		this.btnAddEntry.Label = global::Mono.Unix.Catalog.GetString ("Add Entry");
		this.hbox1.Add (this.btnAddEntry);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnAddEntry]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.btnExit = new global::Gtk.Button ();
		this.btnExit.CanFocus = true;
		this.btnExit.Name = "btnExit";
		this.btnExit.UseUnderline = true;
		this.btnExit.Label = "Exit";
		this.hbox1.Add (this.btnExit);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnExit]));
		w13.Position = 2;
		w13.Expand = false;
		w13.Fill = false;
		this.vbox3.Add (this.hbox1);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox1]));
		w14.PackType = ((global::Gtk.PackType)(1));
		w14.Position = 3;
		w14.Expand = false;
		w14.Fill = false;
		this.Add (this.vbox3);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 356;
		this.DefaultHeight = 541;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.CalendarEntryDate.MonthChanged += new global::System.EventHandler (this.OnCalendarEntryDateMonthChanged);
		this.btnAddEntry.Clicked += new global::System.EventHandler (this.OnBtnAddEntryClicked);
		this.btnExit.Clicked += new global::System.EventHandler (this.OnBtnExitClicked);
	}
}
